language: node_js
os:
  - 'linux'
node_js:
  - '12.0.0'
  - '11.0.0'
  - '10.0.0'
  - '9.0.0'
  - '8.0.0'
  - '7.0.0'
  - '6.0.0'
install:
  - npm install -g typescript@latest
  - npm install
script:
  - npm test
